// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"ddd-demo/app/application/service"
	"ddd-demo/app/interfaces/controller"
	"ddd-demo/infrastructure/repository"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeUserController(db *gorm.DB) *controller.UserController {
	userRepositoryImpl := repository.NewUserRepository(db)
	userServiceImpl := service.NewUserService(userRepositoryImpl)
	userController := controller.NewUserController(userServiceImpl)
	return userController
}

func InitializeOrderController(db *gorm.DB) *controller.OrderController {
	orderRepositoryImpl := repository.NewOrderRepository(db)
	orderServiceImpl := service.NewOrderService(orderRepositoryImpl)
	orderController := controller.NewOrderController(orderServiceImpl)
	return orderController
}
